# Generated by Django 2.1.7 on 2019-03-24 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dominios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dominio',
            name='Owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
