# Generated by Django 2.1.7 on 2019-04-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dominios', '0002_auto_20190324_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominio',
            name='Expired',
            field=models.BooleanField(default=False),
        ),
    ]
